modLoader="javafml" #mandatory
loaderVersion="[40,)"
license="LGPLv3"
issueTrackerURL="https://github.com/yungnickyoung/YUNGs-Extras/issues"

[[mods]]
    modId="yungsextras"
    version="${file.jarVersion}"
	displayName="YUNG's Extras"
    credits="Thanks so much to all my patrons!"
    authors="YUNGNICKYOUNG, Acarii"
    description="Extra structures and vanilla+ content added throughout the game"
    logoFile="logo.png"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/yungs-extras"

[[dependencies.yungsextras]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"

[[dependencies.yungsextras]]
    modId="forge"
    mandatory=true
    versionRange="[40.0.8,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.yungsextras]]
    modId="yungsapi"
    versionRange="[1.18.2-Forge-2.0.7,)"
    mandatory=true
    ordering="NONE"
    side="BOTH"
