modLoader="javafml" #mandatory
loaderVersion="[39,)"
license="LGPLv3"
issueTrackerURL="https://github.com/yungnickyoung/YUNGs-Extras/issues"

[[mods]]
    modId="yungsextras"
    version="${file.jarVersion}"
	displayName="YUNG's Extras"
    credits="Thanks so much to all my patrons!"
    authors="YUNGNICKYOUNG, Acarii"
    description="Extra structures and vanilla+ content added throughout the game"
    logoFile="logo.png"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/yungs-extras"

[[dependencies.yungsextras]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"

[[dependencies.yungsextras]]
    modId="forge"
    mandatory=true
    versionRange="[39.0.0,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.yungsextras]]
    modId="yungsapi"
    versionRange="[1.18.1-Forge-23,)"
    mandatory=true
    ordering="NONE"
    side="BOTH"
