modLoader="javafml" #mandatory
loaderVersion="[35,)"
license="GPLv3"
issueTrackerURL="https://github.com/yungnickyoung/YUNGs-Extras/issues"

[[mods]]
modId="${modId}"
version="${version}"
displayName="${modName}"
credits="${modCredits}"
authors="${modAuthor}"
description="${modDescription}"
logoFile="logo.png"
displayURL="https://www.curseforge.com/minecraft/mc-mods/yungs-extras"

[[dependencies.yungsextras]]
modId="forge"
mandatory=true
versionRange="[35,)"
ordering="NONE"
side="SERVER"

[[dependencies.yungsextras]]
modId="yungsapi"
versionRange="[1.16.4-Forge-6,)"
mandatory=true
ordering="NONE"
side="BOTH"
